server:
  port: 9000
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 300MB
      max-request-size: 300MB

# sunday
sunday:
  swagger:
    title: 接口文档
    enabled: true
    version: 1.0
    author: tellsea
    url: https://github.com/tellsea
    email: 3210054449@qq.com
    description: 更多项目：https://github.com/tellsea
    terms-of-service-url: https://www.apache.org/licenses/LICENSE-2.0.html
    controller-url: cn.tellsea.fileserver.file.controller
